# Generated by Django 3.1.5 on 2023-03-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestroombooking',
            name='guest_room_id',
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='guest_room_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='intender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.extrainfo'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='GuestRoomDetail',
        ),
    ]
